### ISSUE TITLE
Random stop and throws this error

### ISSUE THREAD

**Issue by MoZyo** [wowthecoder/dank-memer-button-update-autotyper#5]
Running via discord_auto_typer[updated].py

Randomly stops and throws this. Encountered this a few times now.

``` Exception in thread Thread-2 (main):
Traceback (most recent call last):
  File "D:\HB Monyo\dank-memer-button-update-autotyper-main\discord_auto_typer[updated].py", line 189, in hl_response
    hint_message = response_dict[0]["embeds"][0]["description"]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Chinno\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Chinno\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\HB Monyo\dank-memer-button-update-autotyper-main\discord_auto_typer[updated].py", line 246, in main
    reply_to_dank_memer(command) #sleep in this function, get the reply first
  File "D:\HB Monyo\dank-memer-button-update-autotyper-main\discord_auto_typer[updated].py", line 88, in reply_to_dank_memer
    hl_response(response_dict)
  File "D:\HB Monyo\dank-memer-button-update-autotyper-main\discord_auto_typer[updated].py", line 201, in hl_response
    trivia_response(response_dict[1:])
NameError: name 'trivia_response' is not defined. Did you mean: 'crime_response'?
```

**Comment by wowthecoder** [comment]
I think I forgot to edit the function name when I copy pasted that section of the code. Just updated the autotyper py file, let me know if you still get any errors.

**Comment by MoZyo** [comment]
I was able to fix it. I lowered the hl and trivia cooldown time in commands because I had patron status, adjusted it to default time and it's okay now.

I also noticed that even when I set 'pls buy life = 1800s", it still executes it within the loop, maybe around 30-60s I think.

Is there a way to set a timer for specific commands?

**Comment by MoZyo** [comment]
Fixed.
